""" This file contains the easily changeable variables for the different
characters and speeds"""

# Screen
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 800

# PLAYER
PLAYER_POSITION = (SCREEN_WIDTH / 2, SCREEN_HEIGHT)
PLAYER_SIZE = (90, 90)
PLAYER_SPEED = 5
PLAYER_THROW_COOLDOWN = 600

# Enemies
ELF_SIZE = (80, 80)
ENEMY_SIZE = (60, 50)
ENEMY_MOVEDOWN = 4
ENEMY_THROW_COOLDOWN = 1600
ENEMY_ROWS = 6
ENEMY_COLUMNS = 8
ENEMY_X_SPACING = 70
ENEMY_Y_SPACING = 55
ENEMY_X_START_SPACING = 0
ENEMY_Y_START_SPACING = 80

# Projectiles
PRESENT_SPEED = 5
PRESENT_SIZE = (20, 20)
SNOWBALL_SPEED = 3
SNOWBALL_SIZE = (20, 20)

# Font
SCORE_FONT = 30
GAME_OVER_FONT = 70
WIN_FONT = 70
LIVES_FONT = 20
LEVEL_FONT = 70

# Lives
LIVES_SIZE = (25, 25)
